# Generated by Django 3.0 on 2020-04-25 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClaimsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.CharField(max_length=50, verbose_name='User ID')),
                ('amount_withdraw', models.CharField(max_length=50, verbose_name='Withdraw')),
                ('purpose', models.CharField(max_length=50, verbose_name='Purpose')),
                ('facility_attended', models.CharField(max_length=50, verbose_name='Facility Attended')),
                ('date_attended', models.CharField(max_length=50, verbose_name='Facility Attended')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Created At')),
            ],
        ),
        migrations.CreateModel(
            name='ContributionModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.CharField(max_length=50, verbose_name='User ID')),
                ('momo', models.CharField(max_length=50, verbose_name='Mobile Money')),
                ('amount', models.CharField(max_length=50, verbose_name='Amount')),
                ('month', models.CharField(blank=True, max_length=50, null=True, verbose_name='Month')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Created At')),
            ],
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.CharField(max_length=50, verbose_name='User ID')),
                ('session_phonenumber', models.CharField(max_length=50, verbose_name='Session Phone Number')),
                ('fullname', models.CharField(max_length=50, verbose_name='Full Name')),
                ('phonenumber', models.CharField(max_length=50, verbose_name='Phone Number')),
                ('gender', models.CharField(max_length=50, verbose_name='Gender')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
        ),
        migrations.CreateModel(
            name='PersonalDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.CharField(max_length=50, verbose_name='Date of birth')),
                ('height', models.CharField(max_length=50, verbose_name='Height')),
                ('occupation', models.CharField(max_length=50, verbose_name='Occupation')),
                ('sector', models.CharField(choices=[('Select an option', 'Select an option'), ('Public Sector', 'Public Sector'), ('Private Sector', 'Private Sector')], default='Select an option', max_length=50, verbose_name='Sector')),
                ('region', models.CharField(max_length=250, verbose_name='Region')),
                ('municipality_district', models.CharField(max_length=50, verbose_name='Municipality / District')),
                ('town', models.CharField(max_length=50, verbose_name='Town')),
                ('residential_address', models.CharField(max_length=50, verbose_name='Residential Address')),
                ('number_of_years_service', models.CharField(max_length=50, verbose_name='Number of years in service')),
                ('number_dependents', models.CharField(max_length=50, verbose_name='Number Dependents')),
                ('registered_nhis', models.BooleanField(default=False, verbose_name='Registered with NHIS')),
                ('private_health', models.BooleanField(default=False, verbose_name='Registered with any private health insurance?')),
                ('pension_scheme', models.CharField(choices=[('Select an option', 'Select an option'), ('Social Security', 'Social Security'), ('Other', 'Other')], max_length=50, verbose_name='Pension Scheme')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Created At')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='personal', to='careapp.UserModel')),
            ],
        ),
    ]
