# Generated by Django 3.0 on 2019-12-18 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClaimsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.CharField(max_length=50, verbose_name='Unique ID')),
                ('amount_withdraw', models.CharField(max_length=50, verbose_name='Withdraw')),
                ('purpose', models.CharField(max_length=50, verbose_name='Purpose')),
                ('facility_attended', models.CharField(max_length=50, verbose_name='Facility Attended')),
                ('date_attended', models.CharField(max_length=50, verbose_name='Facility Attended')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Created At')),
            ],
        ),
        migrations.CreateModel(
            name='ContributionModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.CharField(max_length=50, verbose_name='Unique ID')),
                ('amount', models.CharField(max_length=50, verbose_name='Amount')),
                ('month', models.CharField(max_length=50, verbose_name='Month')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Created At')),
            ],
        ),
        migrations.CreateModel(
            name='HealthData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.CharField(max_length=50, verbose_name='Unique ID')),
                ('bloodglucose', models.CharField(max_length=50, verbose_name='Blood Glucose')),
                ('bloodpressure', models.CharField(max_length=50, verbose_name='Blood Pressure')),
                ('bloodcholesterol', models.CharField(max_length=50, verbose_name='Blood Cholesterol')),
                ('bloodlevel', models.CharField(max_length=50, verbose_name='Blood level (Hemoglobin)')),
                ('weight', models.CharField(max_length=50, verbose_name='Weight')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Created At')),
            ],
        ),
        migrations.CreateModel(
            name='PersonalDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('date_of_birth', models.CharField(max_length=50, verbose_name='Date of birth')),
                ('gender', models.CharField(choices=[('Select an option', 'Select an option'), ('Male', 'Male'), ('Female', 'Female')], default='Select an option', max_length=50, verbose_name='Gender')),
                ('height', models.CharField(max_length=50, verbose_name='Height')),
                ('occupation', models.CharField(max_length=50, verbose_name='Occupation')),
                ('sector', models.CharField(choices=[('Select an option', 'Select an option'), ('Public Sector', 'Public Sector'), ('Private Sector', 'Private Sector')], default='Select an option', max_length=50, verbose_name='Sector')),
                ('region', models.CharField(max_length=250, verbose_name='Region')),
                ('municipality_district', models.CharField(max_length=50, verbose_name='Municipality / District')),
                ('town', models.CharField(max_length=50, verbose_name='Town')),
                ('residential_address', models.CharField(max_length=50, verbose_name='Residential Address')),
                ('number_of_years_service', models.CharField(max_length=50, verbose_name='Number of years in service')),
                ('number_dependents', models.CharField(max_length=50, verbose_name='Number Dependents')),
                ('registered_nhis', models.BooleanField(default=False, verbose_name='Registered with NHIS')),
                ('private_health', models.BooleanField(default=False, verbose_name='Registered with any private health insurance?')),
                ('pension_scheme', models.CharField(max_length=50, verbose_name='Pension Scheme')),
                ('userId', models.CharField(max_length=50, verbose_name='Unique ID')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Created At')),
            ],
        ),
    ]
