# Generated by Django 3.0 on 2020-01-03 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('careapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.CharField(max_length=50, verbose_name='User ID')),
                ('session_phonenumber', models.CharField(max_length=50, verbose_name='Session Phone Number')),
                ('fullname', models.CharField(max_length=50, verbose_name='Full Name')),
                ('phonenumber', models.CharField(max_length=50, verbose_name='Phone Number')),
                ('gender', models.CharField(max_length=50, verbose_name='Gender')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Created At')),
            ],
        ),
        migrations.RemoveField(
            model_name='healthdata',
            name='bloodglucose',
        ),
        migrations.RemoveField(
            model_name='personaldetail',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='personaldetail',
            name='name',
        ),
        migrations.RemoveField(
            model_name='personaldetail',
            name='userId',
        ),
        migrations.AddField(
            model_name='contributionmodel',
            name='momo',
            field=models.CharField(default=True, max_length=50, verbose_name='Mobile Money'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='healthdata',
            name='bloodsugar',
            field=models.CharField(default=True, max_length=50, verbose_name='Blood Sugar'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='healthdata',
            name='phonenumber',
            field=models.CharField(default=True, max_length=50, verbose_name='Phone Number'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contributionmodel',
            name='month',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Month'),
        ),
        migrations.AlterField(
            model_name='healthdata',
            name='userId',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Unique ID'),
        ),
        migrations.AddField(
            model_name='personaldetail',
            name='user',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='careapp.UserModel'),
            preserve_default=False,
        ),
    ]
