# Generated by Django 3.0 on 2020-01-07 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careapp', '0002_auto_20200103_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='claimsmodel',
            name='userId',
            field=models.CharField(max_length=50, verbose_name='User ID'),
        ),
        migrations.AlterField(
            model_name='contributionmodel',
            name='userId',
            field=models.CharField(max_length=50, verbose_name='User ID'),
        ),
        migrations.AlterField(
            model_name='healthdata',
            name='userId',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='User ID'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
    ]
