# Generated by Django 3.0 on 2020-03-09 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('careapp', '0003_auto_20200106_1143'),
        ('careapp', '0003_auto_20200107_2303'),
    ]

    operations = [
    ]
