# Generated by Django 3.0 on 2020-03-24 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('careapp', '0004_merge_20200309_1342'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HealthData',
        ),
        migrations.AlterField(
            model_name='personaldetail',
            name='pension_scheme',
            field=models.CharField(choices=[('Select an option', 'Select an option'), ('Social Security', 'Social Security'), ('Other', 'Other')], max_length=50, verbose_name='Pension Scheme'),
        ),
        migrations.AlterField(
            model_name='personaldetail',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='personal', to='careapp.UserModel'),
        ),
    ]
