# Generated by Django 3.0 on 2020-04-22 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_auto_20200324_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='posted_time',
            field=models.DateField(default=True, verbose_name='Posted Date'),
            preserve_default=False,
        ),
    ]
