# Generated by Django 3.0 on 2020-04-22 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_post_posted_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='posted_time',
        ),
    ]
