# Generated by Django 3.0 on 2020-04-25 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('momo', models.CharField(max_length=50, verbose_name='Mobile Money')),
                ('amount', models.CharField(max_length=50, verbose_name='Amount')),
                ('txtRef', models.CharField(blank=True, max_length=50, null=True, verbose_name='Reference')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Created At')),
            ],
        ),
        migrations.CreateModel(
            name='TransactionHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('momo', models.CharField(max_length=50, verbose_name='Mobile Money')),
                ('amount', models.CharField(max_length=50, verbose_name='Amount')),
                ('txtRef', models.CharField(blank=True, max_length=50, null=True, verbose_name='Reference')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Created At')),
            ],
        ),
        migrations.CreateModel(
            name='Withdraw',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('momo', models.CharField(max_length=50, verbose_name='Mobile Money')),
                ('amount', models.CharField(max_length=50, verbose_name='Amount')),
                ('txtRef', models.CharField(blank=True, max_length=50, null=True, verbose_name='Reference')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Created At')),
            ],
        ),
    ]
