# Generated by Django 3.0 on 2020-04-25 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_customuser_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='userId',
            field=models.CharField(default=True, max_length=50, verbose_name='User ID'),
            preserve_default=False,
        ),
    ]
