# Generated by Django 3.0 on 2020-06-16 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_payment_subscription'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='initiated_on',
            new_name='start_date',
        ),
        migrations.AddField(
            model_name='subscription',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='End Date'),
        ),
    ]
