# Generated by Django 3.0 on 2020-06-16 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20200616_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='package_type',
            field=models.CharField(default=True, max_length=50, verbose_name='Package Type'),
            preserve_default=False,
        ),
    ]
