# Generated by Django 3.0 on 2020-04-25 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('careapp', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Glucose',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, verbose_name='UserName')),
                ('glucose', models.CharField(max_length=50, verbose_name='Glucose')),
                ('date', models.CharField(max_length=50, verbose_name='Date')),
                ('time', models.CharField(max_length=50, verbose_name='Time')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Created At')),
            ],
        ),
        migrations.CreateModel(
            name='Pressure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, verbose_name='UserName')),
                ('systolic', models.CharField(max_length=50, verbose_name='Systolic')),
                ('diastolic', models.CharField(max_length=50, verbose_name='Diastolic')),
                ('date', models.CharField(max_length=50, verbose_name='Date')),
                ('time', models.CharField(max_length=50, verbose_name='Time')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Created At')),
            ],
        ),
        migrations.CreateModel(
            name='Weight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, verbose_name='UserName')),
                ('weight', models.CharField(max_length=50, verbose_name='Weight')),
                ('date', models.CharField(max_length=50, verbose_name='Date')),
                ('time', models.CharField(max_length=50, verbose_name='Time')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Created At')),
            ],
        ),
        migrations.CreateModel(
            name='HealthData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.CharField(blank=True, max_length=50, null=True, verbose_name='User ID')),
                ('phonenumber', models.CharField(max_length=50, verbose_name='Phone Number')),
                ('bloodsugar', models.CharField(max_length=50, verbose_name='Blood Sugar')),
                ('bloodpressure', models.CharField(max_length=50, verbose_name='Blood Pressure')),
                ('bloodcholesterol', models.CharField(max_length=50, verbose_name='Blood Cholesterol')),
                ('bloodlevel', models.CharField(max_length=50, verbose_name='Blood level (Hemoglobin)')),
                ('weight', models.CharField(max_length=50, verbose_name='Weight')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Created At')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='careapp.UserModel')),
            ],
        ),
    ]
