# Generated by Django 3.0 on 2020-01-07 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HealthData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.CharField(blank=True, max_length=50, null=True, verbose_name='User ID')),
                ('phonenumber', models.CharField(max_length=50, verbose_name='Phone Number')),
                ('bloodsugar', models.CharField(max_length=50, verbose_name='Blood Sugar')),
                ('bloodpressure', models.CharField(max_length=50, verbose_name='Blood Pressure')),
                ('bloodcholesterol', models.CharField(max_length=50, verbose_name='Blood Cholesterol')),
                ('bloodlevel', models.CharField(max_length=50, verbose_name='Blood level (Hemoglobin)')),
                ('weight', models.CharField(max_length=50, verbose_name='Weight')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Created At')),
            ],
        ),
    ]
