# Generated by Django 3.0 on 2020-05-05 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0002_auto_20200505_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glucose',
            name='glucose',
            field=models.IntegerField(verbose_name='Glucose'),
        ),
        migrations.AlterField(
            model_name='healthdata',
            name='bloodcholesterol',
            field=models.IntegerField(verbose_name='Blood Cholesterol'),
        ),
        migrations.AlterField(
            model_name='healthdata',
            name='bloodlevel',
            field=models.IntegerField(verbose_name='Blood level (Hemoglobin)'),
        ),
        migrations.AlterField(
            model_name='healthdata',
            name='bloodpressure',
            field=models.IntegerField(verbose_name='Blood Pressure'),
        ),
        migrations.AlterField(
            model_name='healthdata',
            name='bloodsugar',
            field=models.IntegerField(verbose_name='Blood Sugar'),
        ),
        migrations.AlterField(
            model_name='healthdata',
            name='phonenumber',
            field=models.IntegerField(verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='healthdata',
            name='weight',
            field=models.IntegerField(verbose_name='Weight'),
        ),
        migrations.AlterField(
            model_name='pressure',
            name='diastolic',
            field=models.IntegerField(verbose_name='Diastolic'),
        ),
        migrations.AlterField(
            model_name='pressure',
            name='systolic',
            field=models.IntegerField(verbose_name='Systolic'),
        ),
        migrations.AlterField(
            model_name='weight',
            name='weight',
            field=models.IntegerField(verbose_name='Weight'),
        ),
    ]
