# Generated by Django 3.0 on 2020-04-22 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0003_auto_20200422_0603'),
    ]

    operations = [
        migrations.AddField(
            model_name='glucose',
            name='date',
            field=models.CharField(default=True, max_length=50, verbose_name='Date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='glucose',
            name='time',
            field=models.CharField(default=True, max_length=50, verbose_name='Time'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pressure',
            name='date',
            field=models.CharField(default=True, max_length=50, verbose_name='Date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pressure',
            name='time',
            field=models.CharField(default=True, max_length=50, verbose_name='Time'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weight',
            name='date',
            field=models.CharField(default=True, max_length=50, verbose_name='Date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weight',
            name='time',
            field=models.CharField(default=True, max_length=50, verbose_name='Time'),
            preserve_default=False,
        ),
    ]
