# Generated by Django 3.0 on 2020-05-07 09:51

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0004_pressuredataresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glucose',
            name='glucose',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20, verbose_name='Glucose'),
        ),
        migrations.AlterField(
            model_name='healthdata',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20, verbose_name='Glucose'),
        ),
        migrations.AlterField(
            model_name='weight',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20, verbose_name='Glucose'),
        ),
    ]
