# Generated by Django 3.0 on 2020-05-07 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0005_auto_20200507_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glucose',
            name='glucose',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='healthdata',
            name='weight',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='weight',
            name='weight',
            field=models.FloatField(),
        ),
    ]
